"""empty message

Revision ID: 260b647956a
Revises: 5a50bcfb7fe
Create Date: 2015-03-05 21:21:15.425397

"""

# revision identifiers, used by Alembic.
revision = '260b647956a'
down_revision = '5a50bcfb7fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    ### end Alembic commands ###
