"""empty message

Revision ID: 355df5b938b
Revises: 4baff5d1b5d
Create Date: 2015-03-07 12:49:09.007327

"""

# revision identifiers, used by Alembic.
revision = '355df5b938b'
down_revision = '4baff5d1b5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
