"""empty message

Revision ID: 42223fc9c2e
Revises: aeb717ea7e
Create Date: 2015-03-06 09:31:00.595781

"""

# revision identifiers, used by Alembic.
revision = '42223fc9c2e'
down_revision = 'aeb717ea7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
