"""empty message

Revision ID: aeb717ea7e
Revises: 260b647956a
Create Date: 2015-03-06 08:50:38.062955

"""

# revision identifiers, used by Alembic.
revision = 'aeb717ea7e'
down_revision = '260b647956a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
